# Generated by Django 3.0 on 2023-10-01 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('floor_no', models.IntegerField()),
                ('room_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('AC 2-Sharing', 'AC 2-Sharing'), ('AC 3-Sharing', 'AC 3-Sharing'), ('Non AC 2-Sharing', 'Non AC 2-Sharing'), ('Non AC 3-Sharing', 'Non AC 3-Sharing')], max_length=30)),
                ('room_status', models.CharField(choices=[('Full/Unavailable', 'Full/Unavailable'), ('Available', 'Available')], max_length=25)),
                ('total_no_of_beds', models.IntegerField()),
                ('no_of_beds_ava', models.IntegerField()),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('profession', models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employee'), ('Other', 'Other')], max_length=30)),
                ('year', models.IntegerField(null=True)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('aadhar', models.CharField(max_length=12)),
                ('DOJ', models.DateField(auto_now_add=True)),
                ('room_type', models.CharField(choices=[('AC 2-Sharing', 'AC 2-Sharing'), ('AC 3-Sharing', 'AC 3-Sharing'), ('Non AC 2-Sharing', 'Non AC 2-Sharing'), ('Non AC 3-Sharing', 'Non AC 3-Sharing')], max_length=30)),
                ('fee', models.IntegerField()),
                ('payment_status', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Paid', 'Paid')], max_length=20)),
                ('stay_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Guest', 'Guest')], default='Monthly', max_length=20)),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostel.Hostel')),
            ],
        ),
    ]
