# Generated by Django 3.0 on 2023-10-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0002_auto_20231001_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenants',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
