# Generated by Django 3.0 on 2023-10-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0004_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('Viewed', 'Viewed'), ('Not Viewed', 'Not Viewed')], default='Not Viewed', max_length=10),
        ),
    ]
